services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: v0-sandbox-app
    user: "1001:1001"
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-file:./data/prod.db}
      - DIFY_API_KEY=${DIFY_API_KEY:-}
      - DIFY_API_ENDPOINT=${DIFY_API_ENDPOINT:-http://152.136.41.186:32422/v1/workflows/run}
      - COMPONENT_DIFY_API_KEY=${COMPONENT_DIFY_API_KEY:-app-p363bFgzxF8m9J1eyl5wasBT}
      - REQUIRMENT_DIFY_API_KEY=${REQUIRMENT_DIFY_API_KEY:-app-YgkdhmiPidrzl8e1bbaIdNrb}
      - SERVER_HOST=${SERVER_HOST:-wayne.beer}
      - NEXT_PUBLIC_SERVER_HOST=${NEXT_PUBLIC_SERVER_HOST:-wayne.beer}
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN:-wayne.beer}
      - EXTERNAL_PROTOCOL=${EXTERNAL_PROTOCOL:-https}
      - EXTERNAL_PORT=${EXTERNAL_PORT:-}
      - SANDBOX_PREVIEW_URL=${SANDBOX_PREVIEW_URL:-https://sandbox.wayne.beer/}
      - NEXT_PUBLIC_SANDBOX_PREVIEW_URL=${NEXT_PUBLIC_SANDBOX_PREVIEW_URL:-https://sandbox.wayne.beer/}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://wayne.beer}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://wayne.beer}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-}
      - AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME:-}
      # 禁用代理，确保直接连接
      - http_proxy=
      - https_proxy=
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - no_proxy=152.136.41.186
      - NO_PROXY=152.136.41.186
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./sandbox:/app/sandbox
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - v0-sandbox-network

  # Sandbox 预览服务
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: v0-sandbox-preview
    ports:
      - "3100:3100"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3100
      - HOSTNAME=0.0.0.0
    volumes:
      - ./sandbox:/app:rw
    restart: unless-stopped
    networks:
      - v0-sandbox-networz怎么

  # Nginx 服务
  nginx:
    image: nginx:alpine
    container_name: v0-sandbox-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - v0-sandbox-network

networks:
  v0-sandbox-network:
    driver: bridge
