services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    container_name: v0-sandbox-app
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3101:3101"
      - "3102:3102"
      - "3103:3103"
      - "3104:3104"
      - "3105:3105"
      - "3106:3106"
      - "3107:3107"
      - "3108:3108"
      - "3109:3109"
      - "3110:3110"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-file:./data/prod.db}
      - DIFY_API_KEY=${DIFY_API_KEY:-}
      - DIFY_API_ENDPOINT=${DIFY_API_ENDPOINT:-http://152.136.41.186:32422/v1/workflows/run}
      - COMPONENT_DIFY_API_KEY=${COMPONENT_DIFY_API_KEY:-app-p363bFgzxF8m9J1eyl5wasBT}
      - REQUIRMENT_DIFY_API_KEY=${REQUIRMENT_DIFY_API_KEY:-app-YgkdhmiPidrzl8e1bbaIdNrb}
      - SERVER_HOST=${SERVER_HOST:-115.190.100.24}
      - NEXT_PUBLIC_SERVER_HOST=${NEXT_PUBLIC_SERVER_HOST:-115.190.100.24}
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN:-wayne.beer}
      - EXTERNAL_PROTOCOL=${EXTERNAL_PROTOCOL:-https}
      - EXTERNAL_PORT=${EXTERNAL_PORT:-}
      - SANDBOX_PREVIEW_URL=${SANDBOX_PREVIEW_URL:-http://115.190.100.24/sandbox/}
      - NEXT_PUBLIC_SANDBOX_PREVIEW_URL=${NEXT_PUBLIC_SANDBOX_PREVIEW_URL:-http://115.190.100.24/sandbox/}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-}
      - AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      # 禁用代理，确保直接连接
      - http_proxy=
      - https_proxy=
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - no_proxy=152.136.41.186
      - NO_PROXY=152.136.41.186
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      # 开发模式：挂载源代码，代码修改立即生效
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - v0-sandbox-network

  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: v0-sandbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - v0-sandbox-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 服务
  nginx:
    image: nginx:alpine
    container_name: v0-sandbox-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - v0-sandbox-network

volumes:
  redis_data:
    driver: local

networks:
  v0-sandbox-network:
    driver: bridge
