server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: v0-sandbox
    static_configs:
      - targets:
          - localhost
        labels:
          job: v0-sandbox
          __path__: /var/log/app/*.log

    pipeline_stages:
      - match:
          selector: '{job="v0-sandbox"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)\s+(?P<level>\w+)\s+(?P<message>.*)'
            - timestamp:
                source: timestamp
                format: RFC3339
            - labels:
                level:
                message:
