global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # V0 Sandbox 应用监控
  - job_name: "v0-sandbox"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  # Redis 监控
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  # Node Exporter 系统监控
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Docker 监控
  - job_name: "docker"
    static_configs:
      - targets: ["docker-exporter:9323"]

  # Nginx 监控
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
